### ISSUE TITLE
The specified item could not be found in the keychain.

### ISSUE THREAD

**Issue by johnathanz** [dimitri-koenig/alfred-confluence-workflow#7]
I can't seem to get the workflow working. It prob has to do with the way the keychain entry is stored.  I've tried both creating it brand new and also creating it via Safari by logging into Confluence and having it remember password

I get this error in terminal:

```
> security find-internet-password -j "com.alfredapp.dimitrikoenig.confluencesuggest" -g
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
```

**Comment by dimitri-koenig** [comment]
Hm, did you create it by following my tutorial on https://www.dimitrikoenig.net/better-usage-of-sensible-user-data-for-alfred-workflows.html ?
Seems like you put your entry into the wrong keychain. You know, there are many... :-/

**Comment by johnathanz** [comment]
Thanks for the reply. I removed the password, and started it again following your tutorial to the letter.

terminal command now works fine. But I get this error using alfred

![image](https://cloud.githubusercontent.com/assets/1593039/16985073/6b61eab4-4ec1-11e6-800a-4e3a740545aa.png)

**Comment by dimitri-koenig** [comment]
Is it possible that you have secured your Jira Installation with basic auth?

**Comment by johnathanz** [comment]
This is Confluence Cloud / OnDemand.

Does that matter?

**Comment by dimitri-koenig** [comment]
It could matter. Unfortunately I can't test it because I'm not using the cloud version.
