### ISSUE TITLE
Auth config incomplete

### ISSUE THREAD

**Issue by Barzille** [dimitri-koenig/alfred-confluence-workflow#8]
Hi,
I have done as you mentioned, but it sais "Auth config incomple". 
I deleted also all entries of confluence in the keychain and logged in again.
Is there still anything wrong? It's a confluence server version and not the cloud solution.

<img width="530" alt="screenshot_127" src="https://cloud.githubusercontent.com/assets/1096322/23618109/91417a24-028f-11e7-9174-94b6891abda5.png">

**Comment by Barzille** [comment]
Ah, I think it's something about the path of Alfred 3

**Comment by dimitri-koenig** [comment]
I'm planning to switch to Alfred environment variables, which makes such plugins easier to setup. Tomorrow I will look into it.

**Comment by Barzille** [comment]
Ok, thank you.
This is Alfred'sdebug output: 
<img width="1089" alt="screenshot_128" src="https://cloud.githubusercontent.com/assets/1096322/23629318/a7dc5484-02b7-11e7-8467-71b3847ae3c2.png">

**Comment by dimitri-koenig** [comment]
I've uploaded a new workflow file. The main change is: you have to configure your auth data as ENV variables as alfred3 provides this as new feature. Could you quickly try it out?

**Comment by Barzille** [comment]
It's better now but I get this:
![screenshot_141](https://cloud.githubusercontent.com/assets/1096322/23660296/3bc5c52c-0349-11e7-8b73-3c598aab4937.png)
Any idea?

**Comment by dimitri-koenig** [comment]
Debug output?
Which hostUrl do you use?

**Comment by Barzille** [comment]
Ha, it's working. I accidentally mixed password and user in the environment variables :/

**Comment by Barzille** [comment]
btw is this easily adoptable for JIRA?
